"""edit reminder model

Revision ID: 8c02ea87eed7
Revises: 5c7b846a0541
Create Date: 2025-08-29 16:31:45.413564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c02ea87eed7'
down_revision: Union[str, Sequence[str], None] = '5c7b846a0541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'manager_username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('manager_username', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
