"""edit model reminders

Revision ID: ebaaca2cc7a9
Revises: a8874ef48285
Create Date: 2025-08-28 10:52:50.800168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebaaca2cc7a9'
down_revision: Union[str, Sequence[str], None] = 'a8874ef48285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('manager_username', sa.String(), nullable=True))
    op.alter_column('reminders', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('reminders', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reminders', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('reminders', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('reminders', 'manager_username')
    # ### end Alembic commands ###
